import 'package:flutter/material.dart';
import 'package:iconify_flutter_plus/iconify_flutter_plus.dart';
import 'package:iconify_flutter_plus/icons/icon_park_twotone.dart';
import 'package:mindmirror_flutter/config/colors.dart';
import 'package:mindmirror_flutter/database/disclamer_database_helper.dart';

import 'home_screen.dart';

/// A dedicated screen for displaying the critical legal and medical disclaimer.
class DisclaimerScreen extends StatefulWidget {
  const DisclaimerScreen({super.key});

  @override
  State<DisclaimerScreen> createState() => _DisclaimerScreenState();
}

class _DisclaimerScreenState extends State<DisclaimerScreen> {
  bool _isAcknowledged = false;

  void _showAcceptanceDialog() {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return AlertDialog(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          title: Text(
            'Agreement Confirmed',
            style: TextStyle(
              color: AppColors.primaryTeal,
              fontWeight: FontWeight.bold,
            ),
          ),
          content: const Text(
            'Thank you for accepting the legal disclaimer. You can now access the app features. Remember to seek professional help if you are in distress.',
            style: TextStyle(color: AppColors.textPrimary),
          ),
          actions: <Widget>[
            TextButton(
              onPressed: () {
                DisclaimerDatabaseHelper.instance.updateDisclaimerStatus(
                  acknowledged: true,
                );
                Navigator.of(context).pushReplacement(
                  MaterialPageRoute(
                    builder: (BuildContext context) => HomeScreen(),
                  ),
                );
                debugPrint(
                  'Disclaimer accepted. Proceeding to main application.',
                );
              },
              child: Text(
                'Continue to App',
                style: TextStyle(
                  color: AppColors.primaryTeal,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    final horizontalPadding = screenWidth > 600 ? 24.0 : 16.0;

    return Scaffold(
      backgroundColor: AppColors.backgroundLight,
      appBar: AppBar(
        leading: Padding(
          padding: const EdgeInsets.all(15.0),
          child: Iconify(IconParkTwotone.people_safe_one, color: Colors.white),
        ), // widget

        title: const Text(
          'Legal Disclaimer',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        backgroundColor: AppColors.primaryTeal,
        foregroundColor: AppColors.pureWhite,
        elevation: 0,
        centerTitle: true,
      ),
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                padding: EdgeInsets.symmetric(
                  horizontal: horizontalPadding,
                  vertical: 24.0,
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // warning area
                    _buildCrisisWarningBox(),
                    const SizedBox(height: 20),

                    _buildSection(
                      title: 'Professional Advice Disclaimer',
                      content:
                          'This App, MindMirror, is designed only as a screening tool to provide informational insights into patterns detected in your text. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of a qualified healthcare provider or licensed mental health professional with any questions you may have regarding a medical condition or depression. Never disregard professional advice or delay in seeking it because of something you have read or results generated by this App.',
                    ),

                    _buildSection(
                      title: 'Accuracy and Reliability',
                      content:
                          'The App relies on natural language processing (NLP) models which are inherently probabilistic and may produce inaccurate or biased results. The results generated are interpretations of language patterns and are not a clinical assessment. We make no representations or warranties about the accuracy, completeness, or suitability of the information or results provided.',
                    ),

                    _buildSection(
                      title: 'Data and Privacy',
                      content:
                          'By using this App, you acknowledge that you have read and understood our Privacy Policy (link) regarding how your text data is processed and stored. Your privacy is important, but no transmission over the internet is 100% secure.',
                    ),

                    _buildSection(
                      title: 'Limitation of Liability',
                      content:
                          'To the fullest extent permitted by law, the creators of this App shall not be liable for any damages, loss, or injury arising from the use or inability to use the App, including any reliance on the output generated by the depression detection feature.',
                    ),

                    const SizedBox(height: 32),
                    Text(
                      'By tapping "I Agree," you confirm you understand the limitations of this App as a screening tool only.',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: AppColors.textSecondary,
                        fontSize: 12,
                        fontStyle: FontStyle.italic,
                      ),
                    ),
                  ],
                ),
              ),
            ),

            // --- Sticky Footer with Checkbox and Button ---
            _buildFooter(),
          ],
        ),
      ),
    );
  }

  Widget _buildCrisisWarningBox() {
    return Container(
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: AppColors.lightCrisisBackground,
        border: Border(
          left: BorderSide(color: AppColors.crisisRed, width: 4.0),
        ),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(Icons.warning_amber_rounded, color: AppColors.crisisRed),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  'CRITICAL WARNING: If you are in crisis',
                  style: TextStyle(
                    color: AppColors.crisisRed,
                    fontWeight: FontWeight.bold,
                    fontSize: 16,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          const Text(
            'If you are experiencing a mental health emergency or suicidal thoughts, do not rely on this App. Please contact emergency services (e.g., 911 or local equivalent), a crisis hotline, or a mental health professional immediately.',
            style: TextStyle(color: AppColors.textPrimary, fontSize: 13),
          ),
        ],
      ),
    );
  }

  Widget _buildSection({required String title, required String content}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Divider(color: AppColors.borderLight, height: 1),
        const SizedBox(height: 16),
        Text(
          title,
          style: const TextStyle(
            color: AppColors.textPrimary,
            fontWeight: FontWeight.bold,
            fontSize: 18,
          ),
        ),
        const SizedBox(height: 8),
        Text(
          content,
          style: const TextStyle(
            color: AppColors.textPrimary,
            fontSize: 14,
            height: 1.4,
          ),
        ),
        const SizedBox(height: 16),
      ],
    );
  }

  Widget _buildFooter() {
    return Container(
      decoration: BoxDecoration(
        color: AppColors.pureWhite,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, -5),
          ),
        ],
      ),
      padding: const EdgeInsets.only(left: 16, right: 16, top: 16, bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          GestureDetector(
            onTap: () {
              setState(() {
                _isAcknowledged = !_isAcknowledged;
              });
            },
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Checkbox(
                  value: _isAcknowledged,
                  onChanged: (bool? newValue) {
                    setState(() {
                      _isAcknowledged = newValue ?? false;
                    });
                  },
                  activeColor: AppColors.primaryTeal,
                ),
                Expanded(
                  child: Padding(
                    padding: const EdgeInsets.only(top: 10.0),
                    child: RichText(
                      text: TextSpan(
                        style: const TextStyle(
                          fontSize: 14,
                          color: AppColors.textPrimary,
                          height: 1.4,
                        ),
                        children: <TextSpan>[
                          const TextSpan(
                            text: 'I acknowledge and agree to the ',
                          ),
                          TextSpan(
                            text: 'Essential Legal Disclaimer',
                            style: TextStyle(
                              fontWeight: FontWeight.bold,
                              color: AppColors.primaryTeal,
                            ),
                          ),
                          const TextSpan(
                            text: ' and understand the App\'s limitations.',
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),

          SizedBox(
            width: double.infinity,
            height: 50,
            child: ElevatedButton(
              onPressed: _isAcknowledged ? _showAcceptanceDialog : null,
              style: ElevatedButton.styleFrom(
                backgroundColor: _isAcknowledged
                    ? AppColors.primaryTeal
                    : AppColors.lightTeal,
                foregroundColor: AppColors.pureWhite,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10),
                ),
                elevation: 5,
              ),
              child: const Text(
                'I Agree and Start Using the App',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
